---
title: "Binary Classification"
author: ZhengHu
date: 2023-5-14
output: 
  html_notebook: 
    toc: yes
    number_sections: yes
---

```{r}
library(Seurat)
library(caret)
library(xgboost)
library(Matrix)
library(pROC)
library(PRROC)
library(cowplot)
```

```{r}
Barcode <- c("ACB-C","ACB-I","AId-C","AId-I","AUD-I","BLA-C","BLA-I","CP-C","CP-I","DR","ECT-C","ECT-I","ENTl-C","ENTl-I","LHA-I","MD-I","PL-C","RE-I","RSP-C","RSP-I","SC-I","SSp-I", "VIS-I","VTA-I")
```

```{r}
seu <- Adult.Ex.barcode
# 提取 3000 个高变gene
DefaultAssay(seu) <- 'RNA'
seu <- FindVariableFeatures(seu, nfeatures = 3000)
HVGs <- VariableFeatures(seu)
gene_mat <- t(as.matrix(seu@assays$RNA@data[HVGs,]))

plist <- list()
for (i in 1:length(Barcode)){
  Proj <- Barcode[i]
  # 投射模块标签
  label <- seu@meta.data[,Proj]
  label <- label[which(label>=0)]
  label[which(label>0)] <- 1
  label <- factor(label, levels = c(0,1))
  
  # caret 划分训练集和测试集，保留数据分布
  set.seed(20230511)
  X <- gene_mat[which(seu@meta.data[,Proj]>=0),]
  y <- label
  trainIndex <- createDataPartition(y, p = .7, list = FALSE, times = 1)
  X_train <- Matrix(X[trainIndex,], sparse = T)
  y_train <- as.integer(y[trainIndex]) -1
  X_test <- Matrix(X[-trainIndex,], sparse = T)
  y_test <- as.integer(y[-trainIndex]) -1
  dtrain <- xgb.DMatrix(data = X_train, label = y_train)
  dtest <- xgb.DMatrix(data = X_test, label = y_test)
  
  # 用 交叉验证 来对模型进行自动验证，找到最适合的迭代次数
  cv <- xgb.cv(data = dtrain, nrounds = 1000, nfold = 5, early_stopping_rounds=5,
               max_depth = 5, eta = 0.5, objective = "binary:logistic", verbose=F)
  
  # 训练模型
  model_xgb <- xgboost(data=dtrain, max_depth=5, eta=0.5, nthread = 5,
                       nround=cv$best_iteration, objective='binary:logistic')
  
  # 预测
  pre <- predict(model_xgb, newdata=dtest)
  PRROC_obj <- roc.curve(scores.class0=pre, weights.class0=y_test, curve=TRUE)
  df <- data.frame('x'=PRROC_obj$curve[,1],
                 'y'=PRROC_obj$curve[,2],
                 'fill'=PRROC_obj$curve[,3])
  plist[[i]] <-  ggplot(df) +
    geom_line(aes(x=x,y=y,color=fill)) +
    theme_bw() +
    theme(panel.grid=element_blank(), 
          plot.title = element_text(hjust = 0.5, face = "bold")) +
    scale_color_gradientn(colours = rainbow(5)) +
    labs(x='False positive rate', y='Sensitivity', 
         title = paste(Proj,'\n','AUC = ', round(PRROC_obj$auc,7), sep=''))
}
```


```{r fig.height=3, fig.width=6}
plot_grid(plotlist = plist, ncol=6)
```
