---
title: "R Notebook"
output: 
  html_notebook: 
    toc: yes
    css: C:/Users/13081/OneDrive - webmail.hzau.edu.cn/Github/learn/R/notebook.css
    number_sections: yes
---

```{r}
library("factoextra")
```

# Cluster analysis and factoextra
## Partitioning clustering
```{r}
# 1. Loading and preparing data
data("USArrests")
df <- scale(USArrests)
# 2. Compute k-means
set.seed(123)
km.res <- kmeans(df, 4, nstart = 25)
```

```{r fig.height=1.5, fig.width=2}
# 3. Visualize
fviz_cluster(km.res, data = df,
             palette = c("#00AFBB","#2E9FDF", "#E7B800", "#FC4E07"),
             ggtheme = theme_minimal(),
             main = "Partitioning Clustering Plot"
             )
```

## Hierarchical clustering
```{r}
# Compute hierarchical clustering and cut into 4 clusters
res <- hcut(USArrests, k = 4, stand = TRUE)
```

```{r}
# Visualize
fviz_dend(res, rect = TRUE, cex = 0.5, k=4,
          color_labels_by_k=T)
```

## Determine the optimal number of clusters
```{r}
my_data <- scale(USArrests)
fviz_nbclust(my_data, kmeans, method = "gap_stat")
```











