---
title: "Usage with SeuratData"
author: TigerZ
date: 2023-6-22
output: 
  html_notebook: 
    toc: yes
    number_sections: yes
---

以下是一个使用 widget 的示例，从 [SeuratData](https://github.com/satijalab/seurat-data) 包加载 [Seurat](https://satijalab.org/seurat/) 对象。

首先，安装 R 依赖项：

```{r}
install.packages("seurat")
install.packages("devtools")
devtools::install_github("satijalab/seurat-data")
devtools::install_github("mojaveazure/seurat-disk")
```

下载数据集，加载并预处理 Seurat 对象，并配置 Vitessce widget：

```{r}
library(vitessceR)
library(SeuratData)
library(Seurat)

SeuratData::InstallData("pbmc3k")
data("pbmc3k.final")
force(pbmc3k.final)

all.genes <- rownames(pbmc3k.final)
pbmc3k.final <- ScaleData(pbmc3k.final, features = all.genes, do.center = FALSE)

vc <- VitessceConfig$new("My config")
dataset <- vc$add_dataset("My dataset")
dataset <- dataset$add_object(SeuratWrapper$new(
  pbmc3k.final,
  cell_embeddings = c("pca", "umap"),
  cell_embedding_names = c("PCA", "UMAP"),
  cell_set_metas = c("seurat_annotations", "seurat_clusters"),
  out_dir = file.path("data", "seuratdata")
))
scatterplot_pca <- vc$add_view(dataset, Component$SCATTERPLOT, mapping = "PCA")
scatterplot_umap <- vc$add_view(dataset, Component$SCATTERPLOT, mapping = "UMAP")
cell_sets <- vc$add_view(dataset, Component$CELL_SETS)
genes <- vc$add_view(dataset, Component$GENES)
heatmap <- vc$add_view(dataset, Component$HEATMAP)
vc$link_views(
  list(scatterplot_pca, scatterplot_umap, heatmap),
  list(CoordinationType$GENE_EXPRESSION_COLORMAP_RANGE),
  list(c(0.0, 0.035))
)
vc$link_views(
  list(scatterplot_pca, scatterplot_umap),
  list("embeddingCellSetLabelsVisible"),
  list(TRUE)
)
vc$layout(vconcat(
  hconcat(scatterplot_pca, scatterplot_umap),
  hconcat(cell_sets, genes, heatmap)
))
vc$widget(theme = "light")
```








